import os
from pathlib import Path

import pytest

from vindex.compiler.pipeline import compile_video
from vindex.core.schemas.artifacts import VisualMemory


@pytest.mark.skipif(
    not os.getenv("VINDEX_RUN_MODEL_TESTS"),
    reason="VINDEX_RUN_MODEL_TESTS is not set; skipping heavy model E2E tests"
)
def test_e2e_heavy_model_pipeline(tmp_path):
    video_path = Path("test video/sample 2.mp4")
    output_dir = tmp_path / "e2e_heavy_dist"
    
    # Configure actual model dirs
    config = {
        "use_cache": False,
        "asr_model_dir": "/Users/vaibhav/.vindex/models/faster-whisper-medium",
        "det_model_dir": "/Users/vaibhav/.paddlex/official_models/PP-OCRv6_medium_det",
        "rec_model_dir": "/Users/vaibhav/.paddlex/official_models/PP-OCRv6_medium_rec",
        "vlm_model_dir": "/Users/vaibhav/.vindex/models/Qwen2-VL-2B-Instruct-4bit",
        "embed_model_dir": "/Users/vaibhav/.vindex/models/all-MiniLM-L6-v2",
        "similarity_threshold": 0.65,
        "max_gap_ms": 5000,
        "sampling_strategy": "middle",
    }
    
    print("Compiling video with actual heavy models...")
    vm = compile_video(video_path, output_dir, config)
    
    # Assertions
    assert isinstance(vm, VisualMemory)
    assert vm.video_hash != ""
    assert len(vm.timeline.scenes) >= 1
    
    # Verify files written
    assert (output_dir / "visual_memory.json").exists()
    assert (output_dir / "timeline.json").exists()
    assert (output_dir / "scene_index.json").exists()
    assert (output_dir / "ocr.json").exists()
    assert (output_dir / "asr.json").exists()
    assert (output_dir / "visual_memory.md").exists()
    
    # Print the narration text generated by the narrator
    with open(output_dir / "visual_memory.md", "r") as f:
        narration_text = f.read()
    print("Narration Output:\n", narration_text)
