from abc import ABC
from typing import Annotated, Any, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class BaseObservation(BaseModel, ABC):
    """Abstract base class for all vindex observation types (v2.0)."""
    model_config = ConfigDict(frozen=True)

    # Core Metadata (v2.0)
    observation_id: Annotated[str, Field(description="Unique identifier for this observation")] = ""
    schema_version: Annotated[str, Field(description="Schema version of this observation")] = "2.0"
    timestamp_ms: Annotated[int, Field(description="Timestamp in milliseconds from start of video")]
    duration_ms: Annotated[int, Field(description="Duration in milliseconds of this observation")] = 0
    
    # Backwards Compatibility support for v1.0
    source: Annotated[str, Field(description="The source/extractor that generated this observation (v1.0 compat)")] = ""
    
    # Module & Engine metadata
    source_module: Annotated[str, Field(description="The perception module that generated this observation")] = ""
    runtime_name: Annotated[str, Field(description="The runtime engine name")] = ""
    runtime_version: Annotated[str, Field(description="The runtime engine version")] = ""
    model_name: Annotated[str, Field(description="The model name")] = ""
    model_version: Annotated[str, Field(description="The model version")] = ""
    processing_time_ms: Annotated[int, Field(description="Inference time in milliseconds")] = 0
    confidence: Annotated[float, Field(description="Confidence score between 0.0 and 1.0")] = 1.0
    observation_type: Annotated[str, Field(description="Observation type string for Pydantic union discrimination")]


    # Optional Geometry & Image Context
    bbox: Annotated[Optional[list[float]], Field(default=None, description="Normalized bounding box [x, y, w, h]")] = None
    polygon: Annotated[Optional[list[list[float]]], Field(default=None, description="Corner points [[x, y], ...]")] = None
    coordinate_system: Annotated[Optional[str], Field(default=None, description="Coordinate system type (e.g., 'normalized')")] = None
    region_id: Annotated[Optional[str], Field(default=None, description="Target region ID")] = None
    image_reference: Annotated[Optional[str], Field(default=None, description="Path or reference to image file")] = None

    # Traceability Context (v2.0)
    frame_ref: Annotated[Optional[str], Field(default=None, description="Reference to frame path or ID")] = None
    shot_id: Annotated[Optional[str], Field(default=None, description="Reference to shot ID")] = None
    scene_id: Annotated[Optional[str], Field(default=None, description="Reference to scene ID")] = None



class ShotObservation(BaseObservation):
    """Observation representing a detected shot boundary or duration."""
    observation_type: Literal["shot"] = "shot"
    shot_id: Annotated[str, Field(description="Unique identifier for the shot")]
    start_ms: Annotated[int, Field(description="Start time of the shot in milliseconds")]
    end_ms: Annotated[int, Field(description="End time of the shot in milliseconds")]


class FrameObservation(BaseObservation):
    """Observation representing a sampled keyframe."""
    observation_type: Literal["frame"] = "frame"
    shot_id: Annotated[str, Field(description="The shot this keyframe belongs to")]
    frame_path: Annotated[str, Field(description="Local path to the saved keyframe image file")]
    frame_hash: Annotated[str, Field(description="SHA-256 hash of the frame image contents")]


class ASRWordObservation(BaseObservation):
    """Observation representing a single transcribed word."""
    observation_type: Literal["asr"] = "asr"
    word: Annotated[str, Field(description="The transcribed text word")]
    start_ms: Annotated[int, Field(description="Start time of the word in milliseconds")]
    end_ms: Annotated[int, Field(description="End time of the word in milliseconds")]
    confidence: Annotated[float, Field(description="ASR confidence score between 0.0 and 1.0")] = 1.0


class OCRObservation(BaseObservation):
    """Observation representing text detected on screen."""
    observation_type: Literal["ocr"] = "ocr"
    text: Annotated[str, Field(description="Transcribed screen text")]
    bbox: Annotated[list[float], Field(description="Bounding box coordinates in format [x, y, w, h]")]
    frame_ref: Annotated[str, Field(description="Path or ID of the frame this OCR text was found in")]
    confidence: Annotated[float, Field(description="OCR confidence score between 0.0 and 1.0")] = 1.0



class CaptionObservation(BaseObservation):
    """Observation representing a description generated by a Vision-Language Model."""
    observation_type: Literal["caption"] = "caption"
    shot_id: Annotated[str, Field(description="The shot this caption describes")]
    caption_text: Annotated[str, Field(description="The natural language caption text")]
    model_id: Annotated[str, Field(default="unknown", description="Name/ID of the VLM model used")]
    model_version: Annotated[str, Field(default="1.0", description="Version of the VLM model used")]


# --- Schema v2.0 Subclasses ---

class ObjectObservation(BaseObservation):
    """Observation representing a detected object inside a frame."""
    observation_type: Literal["object"] = "object"
    label: Annotated[str, Field(description="Class label of the detected object")]


class MotionObservation(BaseObservation):
    """Observation representing motion intensity and camera movements."""
    observation_type: Literal["motion"] = "motion"
    motion_score: Annotated[float, Field(description="Calculated motion diff score")]
    camera_movement: Annotated[str, Field(description="Identified camera movement (e.g. static, pan, tilt)")]


class LayoutObservation(BaseObservation):
    """Observation representing document or slide layout segmentation."""
    observation_type: Literal["layout"] = "layout"
    reading_order_blocks: Annotated[list[dict[str, Any]], Field(default_factory=list, description="Sequence of text reading blocks")]


class ColorObservation(BaseObservation):
    """Observation representing dominant color palette and screen brightness."""
    observation_type: Literal["color"] = "color"
    dominant_palette: Annotated[list[str], Field(default_factory=list, description="List of dominant colors as Hex strings")]
    brightness: Annotated[float, Field(description="Average frame brightness value between 0.0 and 1.0")]


class AudioEventObservation(BaseObservation):
    """Observation representing a non-speech audio event (laughter, applause, etc.)."""
    observation_type: Literal["audio_event"] = "audio_event"
    label: Annotated[str, Field(description="Type/label of the audio event")]


# --- Discriminated Union Type Mapping for Polymorphism ---
ObservationUnion = Annotated[
    Union[
        ShotObservation,
        FrameObservation,
        ASRWordObservation,
        OCRObservation,
        CaptionObservation,
        ObjectObservation,
        MotionObservation,
        LayoutObservation,
        ColorObservation,
        AudioEventObservation,
    ],
    Field(discriminator="observation_type")
]

